### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-operator-openshift#3]
- [x] project id is operators-openshift and repo is draft-guide-operators-openshift but the guide content and title use  Open Liberty Operator. Should use singlar in project id and repo?
- **Additional prerequisites**
  - [ ] need a link how to install/config OpenShift cluster and/or OpenShift Container Platform
- **Installing the Open Liberty Operator**
  - [ ] is it possible to reduce the spacing below **Using the CLI** and **Using the web console**?
- **Deploying the Kafka service to OpenShift**
  - [x] is the output of `oc get all` too big? If not, can show an example of the output
- **Deploying the system and inventory applications to OpenShift**
  - [x] can following command work in Windows ?
    ```
    oc process -f build.yaml -p APP_NAME=system | oc create -f -
    oc process -f build.yaml -p APP_NAME=inventory | oc create -f -
    ```
  - [ ] show the output for `oc` commands if the output not too big and can make readers more clear
  - [ ] instead have 3 subsections, consider to promote them to main sections
- **Scaling up the system application**
  - [x] show output of below "Revisit the inventory application and you now see three elements."
- [x] better add a teardown section
- **Where to next?**
  - [x] at least can consider to add the MP reactive guide, okd, and openshift guides
- [x] apply https://github.com/openliberty/guides-common/issues/436 for all pom.xml
- [x] update all index.html and server.xml from the MP reactive messaging guide
- [x] update all Dockerfile 
  - update org.opencontainers.image.source and description
  - can do `RUN configure.sh` and remove the comment 
- [x] make sure the guide can run in Windows
- [ ] change "system/inventory application" to "system/inventory microservice"

**Comment by MaiHameed** [comment]
> project id is operators-openshift and repo is draft-guide-operators-openshift but the guide content and title use Open Liberty Operator. Should use singlar in project id and repo?

Asked Harry to change the repo name to singular `draft-guide-operator-openshift` and updated the `projectid` accordingly.

> need a link how to install/config OpenShift cluster and/or OpenShift Container Platform

This is difficult to achieve, since there are many ways of obtaining an OpenShift cluster, with many different types. OKD for 3.x, CRC for 4.x, OCP, OpenShift Dedicated/Online, etc. I'm certain that every cluster will functionally be the same, so it doesn't matter which cluster the user picks, which is why I purposefully left this blank. Should I suggest that the user pick an option from the official Red Hat website?

> is it possible to reduce the spacing below Using the CLI and Using the web console?

Unfortunately not, currently it's formatted in the `README` like so:
```
*Using the CLI*

To install the Open Liberty Operator through the CLI, follow the instructions from the
https://github.com/OpenLiberty/open-liberty-operator#operator-installation[official GitHub repository^].
```

If I reduce the space to:
```
*Using the CLI*
To install the Open Liberty Operator through the CLI, follow the instructions from the
https://github.com/OpenLiberty/open-liberty-operator#operator-installation[official GitHub repository^].
```

The site updates to:

![image](https://user-images.githubusercontent.com/26514093/81325838-f2a22d00-9066-11ea-889d-d9beaf74b3e5.png)

> can following command work in Windows ?
> make sure the guide can run in Windows

All of the commands should be run from within the cluster, and OpenShift clusters run on Unix based OSs, so the commands will work on any OpenShift cluster. I added a sentence telling the user to make sure that they are logged into their OpenShift cluster and running commands from within.

> instead have 3 subsections, consider to promote them to main sections

I did this because the three subsections (packaging the applications, building and pushing the images, and deploying the images) are part of the whole `Deploying the system and inventory applications to OpenShift` section. This keeps it consistent with the other main sections, `installing the operator` and `installing kafka`, it's just that the `system` and `inventory` installation section is a little longer, so I added sub-headings. If you still think I should promote the sub-headings to main headings let me know.

> apply OpenLiberty/guides-common#436 for all pom.xml
> update all index.html and server.xml from the MP reactive messaging guide

Addressed in this commit: https://github.com/OpenLiberty/draft-guide-operator-openshift/commit/f5e7a4195c54c2a6a724914cb4c2633c68b4e0ee

> change "system/inventory application" to "system/inventory microservice"

I purposefully avoided using the terms `microservice` or `service` because a OpenShift `service` is a resource, and I didn't want to confuse the user on the difference between the two, so I opted to use different terminology to differentiate. If you still think I should change it, let me know.

**Comment by gkwan-ibm** [comment]
- **Additional prerequisites**
  - [ ] "...this guide uses OpenShift Container Platform 4.3." I think you tried the guide on "OpenShift Container Platform 4.3", but the guide does not ask readers to install "OpenShift Container Platform 4.3." of xxxx. Rewrite this paragraph to tell the fact that the guide need to run on an OS cluster either from any type OKD for 3.x, CRC for 4.x, OCP, OpenShift Dedicated/Online, etc
- **Deploying the system and inventory applications to OpenShift**
  - **Building and pushing the images**
    - [ ] just make sure Windows can handle the pipe char `|` correctly
    - [ ] output box after "oc get builds" command should not be a green command box
    - [ ] show the output for `oc describe...` commands if the output not too big and can make readers more clear
  - **Deploying the images**
    - [ ] show the output for `oc describe...` commands if the output not too big and can make readers more clear
- [ ] at **Deploying the images** section, `---` in deploy.yaml at the right pane is shown normally but at the **Scaling up the system application** section, `---` in deploy.yaml at the right pane is different. Something affected?

**Comment by MaiHameed** [comment]
> just make sure Windows can handle the pipe char | correctly

The commands with the pipe character will be run in the OpenShift cluster, and all clusters run on UNIX OSs, so there will be no issue here

> show the output for oc describe... commands if the output not too big and can make readers more clear 

This was purposefully left out as the output is too large.

> at Deploying the images section, --- in deploy.yaml at the right pane is shown normally but at the Scaling up the system application section, --- in deploy.yaml at the right pane is different. Something affected?

Yes, I opened an issue here: https://github.com/OpenLiberty/openliberty.io/issues/1634 the issue was that the file inclusion command: `[source, YAML, linenums, role='code_column']` didn't recognize the uppercase `YAML`, Steven updated it so it recognizes both cases (upper and lower).

**Comment by gkwan-ibm** [comment]
- [ ] should Dockerfile uncomment `RUN configure.sh` and remove comment `# It is recommended to run the configure.sh...`
- [ ] update the labels `org.opencontainers.image.source` and `summary` in  Dockerfile 
- [ ] show partial important out for `oc describe... `
- [ ] fill up `(Explain operators)`
- [ ] update models/pom.xml to standard

**Comment by gkwan-ibm** [comment]
- **Deploying the images**
  - [ ] the system hotspot to deploy.yaml not right
  - [ ] "...communicate with [hotspot=systemEnv file=1]Kafka are provided." not right
- **Accessing the inventory application**
  - [ ] better to show an example output for `oc get routes`, so that readers know how to get the host, 
    - "... that you substitute the appropriate `HOST` by `inventory-xxxxx`:
- delploy.yaml
  - [ ] `apiVersion: openliberty.io/v1beta1` Is there any better version instead of `v1beta1`?

**Comment by MaiHameed** [comment]
> apiVersion: openliberty.io/v1beta1 Is there any better version instead of v1beta1?

Yes, it must be. the OL operator is only watching that specific apiVersion/kind. The CRD that the Operator watches is here: https://github.com/OpenLiberty/open-liberty-operator/tree/master/pkg/apis/openliberty/v1beta1

When searching for the versions installed on the cluster:
```
[root@poops-inf ~]# oc api-versions | grep openliberty
openliberty.io/v1beta1
```
